package DataAdapter;

public enum Subject {
    ECONOMY_AND_LAW,
    HEALTH_AND_DENTAL_TREATMENT,
    IT,
    ART,
    CULTURE_RELIGION_HISTORY_AND_PHILOSOPHY,
    TEACHER_EDUCATION_AND_PEDAGOGY,
    SCIENCE_AND_MATH,
    SOCIETY_AND_BEHAVIOR_SCIENCE,
    LANGUAGE
}
